spring:
  profiles:
    active: ${ENVIRONMENT:local}
  application:
    name: product-microservice
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    api-docs:
      path: /api-docs
client:
  value: product-dummy-client
  url: https://dummyjson.com
jwt-secret: xpto-1172

